### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[59, 84, 50, 69],
       [94, 81, 84, 68],
       [89, 28, 16, 39],
       [ 2, 26, 78, 64],
       [11, 14, 58, 34],
       [91, 82, 79,  6]])

In [3]:
np.sort(a)[::-1]

array([82, 80, 77, 64, 44, 38, 32, 31, 31, 28, 25, 24, 20, 15, 13])

In [4]:
np.sort(b,axis=0)

array([[ 2, 14, 16,  6],
       [11, 26, 50, 34],
       [59, 28, 58, 39],
       [89, 81, 78, 64],
       [91, 82, 79, 68],
       [94, 84, 84, 69]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 32,  25,  20,  15,  77,  38,  31,  24,  31,  80,  64,  28,  82,
        44,  13, 200])

In [6]:
b

array([[59, 84, 50, 69],
       [94, 81, 84, 68],
       [89, 28, 16, 39],
       [ 2, 26, 78, 64],
       [11, 14, 58, 34],
       [91, 82, 79,  6]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[5.90000000e+01, 8.40000000e+01, 5.00000000e+01, 6.90000000e+01,
        4.79734593e-01],
       [9.40000000e+01, 8.10000000e+01, 8.40000000e+01, 6.80000000e+01,
        6.25306349e-01],
       [8.90000000e+01, 2.80000000e+01, 1.60000000e+01, 3.90000000e+01,
        8.10639777e-01],
       [2.00000000e+00, 2.60000000e+01, 7.80000000e+01, 6.40000000e+01,
        1.65256850e-01],
       [1.10000000e+01, 1.40000000e+01, 5.80000000e+01, 3.40000000e+01,
        7.60132196e-01],
       [9.10000000e+01, 8.20000000e+01, 7.90000000e+01, 6.00000000e+00,
        1.45028118e-02]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [17]:

print(np.expand_dims(a,axis=1))
print(np.expand_dims(a,axis=1).shape)


[[32]
 [25]
 [20]
 [15]
 [77]
 [38]
 [31]
 [24]
 [31]
 [80]
 [64]
 [28]
 [82]
 [44]
 [13]]
(15, 1)


### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 4,  9, 10, 12]),)

In [20]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([32, 25, 20, 15,  0, 38, 31, 24, 31,  0,  0, 28,  0, 44, 13])

In [21]:
np.where(a%2 == 0,0,a)

array([ 0, 25,  0, 15, 77,  0, 31,  0, 31,  0,  0,  0,  0,  0, 13])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
# code
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [23]:
np.argmax(a)

12

In [24]:
b

array([[59, 84, 50, 69],
       [94, 81, 84, 68],
       [89, 28, 16, 39],
       [ 2, 26, 78, 64],
       [11, 14, 58, 34],
       [91, 82, 79,  6]])

In [25]:
np.argmax(b,axis=0)

array([1, 0, 1, 0])

In [26]:
np.argmax(b,axis=1)

array([1, 0, 0, 2, 2, 0])

In [27]:
# np.argmin
np.argmin(a)

14

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [29]:
np.cumsum(a)

array([ 32,  57,  77,  92, 169, 207, 238, 262, 293, 373, 437, 465, 547,
       591, 604])

In [30]:
b

array([[59, 84, 50, 69],
       [94, 81, 84, 68],
       [89, 28, 16, 39],
       [ 2, 26, 78, 64],
       [11, 14, 58, 34],
       [91, 82, 79,  6]])

In [31]:
np.cumsum(b,axis=1)

array([[ 59, 143, 193, 262],
       [ 94, 175, 259, 327],
       [ 89, 117, 133, 172],
       [  2,  28, 106, 170],
       [ 11,  25,  83, 117],
       [ 91, 173, 252, 258]])

In [32]:
np.cumsum(b)

array([  59,  143,  193,  262,  356,  437,  521,  589,  678,  706,  722,
        761,  763,  789,  867,  931,  942,  956, 1014, 1048, 1139, 1221,
       1300, 1306])

In [33]:
# np.cumprod
np.cumprod(a)

array([                  32,                  800,                16000,
                     240000,             18480000,            702240000,
                21769440000,         522466560000,       16196463360000,
           1295717068800000,    82925892403200000,  2321924987289600000,
        5930408220651683840,  2683544676740366336, -2007407349794340864])

In [34]:
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [36]:
np.percentile(a,50)

31.0

In [37]:
np.median(a)

31.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [38]:
# code
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [39]:
np.histogram(a,bins=[0,50,100])

(array([11,  4]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [40]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [41]:
# code
a


array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [42]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([20, 80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [43]:
# code
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [44]:
np.flip(a)

array([13, 44, 82, 28, 64, 80, 31, 24, 31, 38, 77, 15, 20, 25, 32])

In [45]:
b

array([[59, 84, 50, 69],
       [94, 81, 84, 68],
       [89, 28, 16, 39],
       [ 2, 26, 78, 64],
       [11, 14, 58, 34],
       [91, 82, 79,  6]])

In [46]:
np.flip(b,axis=1)

array([[69, 50, 84, 59],
       [68, 84, 81, 94],
       [39, 16, 28, 89],
       [64, 78, 26,  2],
       [34, 58, 14, 11],
       [ 6, 79, 82, 91]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [47]:
# code
a

array([32, 25, 20, 15, 77, 38, 31, 24, 31, 80, 64, 28, 82, 44, 13])

In [48]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [49]:
# code
a

array([110, 530,  20,  15,  77,  38,  31,  24,  31,  80,  64,  28,  82,
        44,  13])

In [50]:
np.delete(a,[0,2,4])

array([530,  15,  38,  31,  24,  31,  80,  64,  28,  82,  44,  13])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [51]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.intersect1d(m,n)

array([3, 4, 5])

In [53]:
np.setdiff1d(n,m)

array([6, 7])

In [54]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [55]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [56]:
# code
a

array([110, 530,  20,  15,  77,  38,  31,  24,  31,  80,  64,  28,  82,
        44,  13])

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 25, 75, 38, 31, 25, 31, 75, 64, 28, 75, 44, 25])

In [58]:
# 17. np.swapaxes

In [59]:
# 18. np.uniform

In [60]:
# 19. np.count_nonzero

In [61]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [62]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [63]:

# 25. np.allclose and equals