# Pandas 
     - Data analysis library 
     - Series   Single Dimension
     - Dataframe  Multidimensional

In [5]:
import pandas as pd

# Series

In [7]:
s1 = pd.Series([1,2,3,4])

In [8]:
type(s1)

pandas.core.series.Series

In [9]:
print(s1)

0    1
1    2
2    3
3    4
dtype: int64


In [10]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [12]:
s1.index = ["one", 'two','three','four']

In [13]:
s1

one      1
two      2
three    3
four     4
dtype: int64

In [14]:
s1['one']

1

In [15]:
s1.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [16]:
s1[0]

1

In [27]:
s2= pd.Series([22,33,44,55,100], index=['apples', 'oranges','bananas','gauvas', 'two'])
s2

apples      22
oranges     33
bananas     44
gauvas      55
two        100
dtype: int64

In [28]:
s1  = s1*10

In [29]:
s1

one      100
two      200
three    300
four     400
dtype: int64

In [30]:
s2

apples      22
oranges     33
bananas     44
gauvas      55
two        100
dtype: int64

In [31]:
s1  + s2 

apples       NaN
bananas      NaN
four         NaN
gauvas       NaN
one          NaN
oranges      NaN
three        NaN
two        300.0
dtype: float64

In [32]:
s3 = pd.Series(range(10))
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [35]:
s4 = pd.Series(range(10,21))
s4

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [36]:
s3+ s4

0     10.0
1     12.0
2     14.0
3     16.0
4     18.0
5     20.0
6     22.0
7     24.0
8     26.0
9     28.0
10     NaN
dtype: float64

In [38]:
import numpy as np
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [39]:
arr2 = np.arange(6)

In [40]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [44]:
s2

apples      22
oranges     33
bananas     44
gauvas      55
two        100
dtype: int64

In [45]:
s2[2:4]

bananas    44
gauvas     55
dtype: int64

In [46]:
s2['oranges':'gauvas']

oranges    33
bananas    44
gauvas     55
dtype: int64

In [47]:
s2[2:4] = 23

In [48]:
s2

apples      22
oranges     33
bananas     23
gauvas      23
two        100
dtype: int64

# Lambda Functions : Anonymous Functions (IIF)

In [75]:
new = pd.Series([99, 100, 89, 50 ,45,30], index=['Ahmed', 'Ali', 'Faisal', 'Hassan', 'Aqsa', 'Waji'])

In [76]:
new

Ahmed      99
Ali       100
Faisal     89
Hassan     50
Aqsa       45
Waji       30
dtype: int64

In [53]:
def myfunc(marks):
    return marks/100

In [72]:
new = new.apply(myfunc)

In [81]:
new = new.apply(lambda x: np.where(x>40, "Pass", "Fail"))

In [58]:
s1

one      100
two      200
three    300
four     400
dtype: int64

In [59]:
s2

apples      22
oranges     33
bananas     23
gauvas      23
two        100
dtype: int64

In [60]:
s1 + s2

apples       NaN
bananas      NaN
four         NaN
gauvas       NaN
one          NaN
oranges      NaN
three        NaN
two        300.0
dtype: float64

In [61]:
s2.index

Index(['apples', 'oranges', 'bananas', 'gauvas', 'two'], dtype='object')

In [64]:
s5 = pd.Series([1,2,3,4,5],index=s2.index)
s5

apples     1
oranges    2
bananas    3
gauvas     4
two        5
dtype: int64

In [67]:
s6 = pd.Series(100,index=s2.index)
s6

apples     100
oranges    100
bananas    100
gauvas     100
two        100
dtype: int64

In [70]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [78]:
new.count()

6

In [82]:
new.value_counts()

Pass    5
Fail    1
dtype: int64

In [85]:
new[['Ahmed','Ali' ]]

Ahmed    Pass
Ali      Pass
dtype: object

In [88]:
s7 = pd.Series([1,2,3,np.nan, np.nan])
s7

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [107]:
np.random.seed(1)
s1 = pd.Series(np.random.randn(3))
s2 = pd.Series(np.random.randn(3))

In [108]:
s1

0    1.624345
1   -0.611756
2   -0.528172
dtype: float64

In [91]:
s2

0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [109]:
combined = pd.concat([s1, s2])
combined

0    1.624345
1   -0.611756
2   -0.528172
0   -1.072969
1    0.865408
2   -2.301539
dtype: float64

In [115]:
combined.reset_index(drop=True,inplace=True)

In [116]:
combined

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
5   -2.301539
dtype: float64

In [117]:
combined[4] = 2345
combined

0       1.624345
1      -0.611756
2      -0.528172
3      -1.072969
4    2345.000000
5      -2.301539
dtype: float64

In [118]:
del combined[4]

In [119]:
combined

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
5   -2.301539
dtype: float64

In [125]:
del combined[3]

In [128]:
combined[1:5] =100
combined

0      1.624345
1    100.000000
2    100.000000
5    100.000000
dtype: float64

In [130]:
newCom = combined.copy()   # copy by value
newCom = combined[:,:]

In [132]:
oldCom  = newCom   # copy by refernce 

In [134]:
oldCom

0      1.624345
1    100.000000
2    100.000000
5    100.000000
dtype: float64

# Pandas Data Frame

In [140]:
students = {'rolls':[1,2,3,4,5,6],
            'names':['Ali','Amjad', 'Saima', 'Qaiser','Hamid','Nasir'], 
            'courses':['Python', 'Pandas', 'Numpy','Pandas', 'Numpy', "Python"], 
            'mode':['Online', 'Onsite','Online', 'Onsite','Online', 'Onsite']}


In [145]:
# Creating a data frame
df  = pd.DataFrame(students)
df

rolls   names courses    mode
0      1     Ali  Python  Online
1      2   Amjad  Pandas  Onsite
2      3   Saima   Numpy  Online
3      4  Qaiser  Pandas  Onsite
4      5   Hamid   Numpy  Online
5      6   Nasir  Python  Onsite

In [148]:
type(df[['rolls', 'names']])

pandas.core.frame.DataFrame

In [150]:
type(df['rolls'])

pandas.core.series.Series

In [151]:
type(df[['rolls']])

pandas.core.frame.DataFrame

In [155]:
np.array([[9]]).ndim

2

In [166]:
lst=[[55,66,77],[2,4,5],[4,5,6]]

In [167]:
lst

[[55, 66, 77], [2, 4, 5], [4, 5, 6]]

In [168]:
pd.DataFrame(lst,index=[1,2,3],columns=["a","b","c"] )

a   b   c
1  55  66  77
2   2   4   5
3   4   5   6

In [169]:
#Accessing data
# Columns

In [171]:
df['courses']

0    Python
1    Pandas
2     Numpy
3    Pandas
4     Numpy
5    Python
Name: courses, dtype: object

In [173]:
df[['courses', 'names']]

courses   names
0  Python     Ali
1  Pandas   Amjad
2   Numpy   Saima
3  Pandas  Qaiser
4   Numpy   Hamid
5  Python   Nasir

In [174]:
df['Country'] = "Pakistan"
df

rolls   names courses    mode   Country
0      1     Ali  Python  Online  Pakistan
1      2   Amjad  Pandas  Onsite  Pakistan
2      3   Saima   Numpy  Online  Pakistan
3      4  Qaiser  Pandas  Onsite  Pakistan
4      5   Hamid   Numpy  Online  Pakistan
5      6   Nasir  Python  Onsite  Pakistan

In [175]:
df['Ages'] = [23,34,23,21,20,19]
df

rolls   names courses    mode   Country  Ages
0      1     Ali  Python  Online  Pakistan    23
1      2   Amjad  Pandas  Onsite  Pakistan    34
2      3   Saima   Numpy  Online  Pakistan    23
3      4  Qaiser  Pandas  Onsite  Pakistan    21
4      5   Hamid   Numpy  Online  Pakistan    20
5      6   Nasir  Python  Onsite  Pakistan    19

In [177]:
dic = {'Ali':34, 'Amjad':45, "Saima":23, "Hamid":34, "Nasir":20,'Qaiser':45}

In [208]:
df['newAges'] = df.names.map(dic)

In [183]:
df['Status'] = ["Pass" if age>25 else "Fails" for age in df['Ages']]

In [209]:
df

rolls   names courses    mode   Country  Ages Status         City  \
0      1     Ali  Python  Online  Pakistan    23  Fails  Outside Khi   
1      2   Amjad  Pandas  Onsite  Pakistan    34   Pass      Karachi   
2      3   Saima   Numpy  Online  Pakistan    23  Fails  Outside Khi   
3      4  Qaiser  Pandas  Onsite  Pakistan    21  Fails      Karachi   
4      5   Hamid   Numpy  Online  Pakistan    20  Fails  Outside Khi   
5      6   Nasir  Python  Onsite  Pakistan    19  Fails      Karachi   

  Generation Generation Next  newAges  
0      Young           Young       34  
1      Young           Young       45  
2      Young           Young       23  
3      Young           Young       45  
4      Young           Young       34  
5  Teen Ager       Teen Ager       20

In [190]:
df['City'] = df['mode'].apply(lambda x: 'Karachi' if x=="Onsite" else "Outside Khi")

In [191]:
df

rolls   names courses    mode   Country  Ages Status         City
0      1     Ali  Python  Online  Pakistan    23  Fails  Outside Khi
1      2   Amjad  Pandas  Onsite  Pakistan    34   Pass      Karachi
2      3   Saima   Numpy  Online  Pakistan    23  Fails  Outside Khi
3      4  Qaiser  Pandas  Onsite  Pakistan    21  Fails      Karachi
4      5   Hamid   Numpy  Online  Pakistan    20  Fails  Outside Khi
5      6   Nasir  Python  Onsite  Pakistan    19  Fails      Karachi

In [193]:
def generationAssign(age):
    if age <20:
        return "Teen Ager"
    elif age<40:
        return "Young"
    elif age <60:
        return "Matured"
    else:
        return 'Senior'

In [201]:
df['Generation Next'] = df.Ages.apply(generationAssign)

In [202]:
df

rolls   names courses    mode   Country  Ages Status         City  \
0      1     Ali  Python  Online  Pakistan    23  Fails  Outside Khi   
1      2   Amjad  Pandas  Onsite  Pakistan    34   Pass      Karachi   
2      3   Saima   Numpy  Online  Pakistan    23  Fails  Outside Khi   
3      4  Qaiser  Pandas  Onsite  Pakistan    21  Fails      Karachi   
4      5   Hamid   Numpy  Online  Pakistan    20  Fails  Outside Khi   
5      6   Nasir  Python  Onsite  Pakistan    19  Fails      Karachi   

  Generation Generation Next  
0      Young           Young  
1      Young           Young  
2      Young           Young  
3      Young           Young  
4      Young           Young  
5  Teen Ager       Teen Ager

In [196]:
df.to_excel("student.xlsx")

In [197]:
a =np.array([1,2,3])

In [198]:
a

array([1, 2, 3])

In [199]:
a = a*10

array([10, 20, 30])

In [200]:
a

array([1, 2, 3])

In [205]:
df['Generation Next']

0        Young
1        Young
2        Young
3        Young
4        Young
5    Teen Ager
Name: Generation Next, dtype: object

In [210]:
data = pd.read_csv("astronauts.csv")

In [211]:
data

Name    Year  Group   Status Birth Date  \
0          Joseph M. Acaba  2004.0   19.0   Active  5/17/1967   
1           Loren W. Acton     NaN    NaN  Retired   3/7/1936   
2         James C. Adamson  1984.0   10.0  Retired   3/3/1946   
3          Thomas D. Akers  1987.0   12.0  Retired  5/20/1951   
4              Buzz Aldrin  1963.0    3.0  Retired  1/20/1930   
..                     ...     ...    ...      ...        ...   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
0        Inglewood, CA   Male   
1         Lewiston, MT   Male   
2           Warsaw, NY   Male   
3        St. Louis, MO   Male   
4        Montclair, NJ   Male   
..                 ...    ...   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
0    University of California-Santa Barbara; Univer...   
1     Montana State University; University of Colorado   
2            US Military Academy; Princeton University   
3                         University of Missouri-Rolla   
4                             US Military Academy; MIT   
..                                                 ...   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
0                     Geology                                   Geology   
1         Engineering Physics                             Solar Physics   
2                 Engineering                     Aerospace Engineering   
3         Applied Mathematics                       Applied Mathematics   
4      Mechanical Engineering                              Astronautics   
..                        ...                                       ...   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
0             NaN                        NaN              2   
1             NaN                        NaN              1   
2         Colonel          US Army (Retired)              2   
3         Colonel     US Air Force (Retired)              4   
4         Colonel     US Air Force (Retired)              2   
..            ...                        ...            ...   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
0                 3307            2              13.0   
1                  190            0               0.0   
2                  334            0               0.0   
3                  814            4              29.0   
4                  289            2               8.0   
..                 ...          ...               ...   
352               4044            7              41.0   
353                  0           