In [ ]:
#Numpy
# Numerical 


In [1]:
import numpy as np


In [6]:
# Creating an array using a python list
x=np.array([22,33,44,55])
x
x.size


4

In [9]:
# 1d = Vector
# 2d = Matrix
# 3d = Cube
# nd = .....
x.shape   
x.ndim # Will return 1 dimension

1

In [11]:
arr1d=np.arange(10)
arr1d.shape
arr2d=np.array([[1,2,3],[11,22,33],[111,222,333]])
arr2d.shape

(3, 3)

In [18]:
arr2d=np.arange(20).reshape(1,20)
#  vakue in arange is the number of elements to be included
# 1st element in the reshaoe is no of rows and 2nd elements is columns in a row
# So the above statement tell python to divide 20 elements in 2d with 1 row and 20 columns
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [19]:
arr2d=np.arange(20).reshape(5,4)
#  vakue in arange is the number of elements to be included
# 1st element in the reshaoe is no of rows and 2nd elements is columns in a row
# So the above statement tell python to divide 20 elements in 2d with 5 row and 4 columns
# Please note that total no of elements should be that all elements can be adjusted in the shape

arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
arr2d[2,3] # Will return 11
arr2d[3][2] # will return 14


14

In [24]:
arr3d=np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [33]:
# LEts assumne we have array and we want  to mutiple every element of array with 4
# In python we can use for loop to this action
# In numoy we cxan also do this using a operation like a simple variable as
arr=np.arange(10)
arr=arr * 2
arr
# Same is valuid for any dimensional variable
arr2d
arr2d=arr2d * 3
arr2d

# To multiple only one dimension
arr2d[0]=arr2d[0]*5
arr2d

array([   0, 1215, 2430, 3645])

In [36]:
a=np.arange(25).reshape(5,5)
b=np.arange(25,50).reshape(5,5)
c=a+b #m This is known as Mirror Operations or Elements wise operations
c

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [37]:
# Now if me want do the liner algebra matix multiplication where 1st matrix row is mutiplied with column of 2nd matrix and so on
# for that we use
a=np.arange(25).reshape(5,5)
b=np.arange(25,50).reshape(5,5)
c=a@b # Dot will mutiple like liner algebra where 1st row of a matrix is mutipled with row of 2nd matrix
c

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [45]:
# Slicing in Numpy
ar = np.arange(25).reshape(5,5)
ar
# For slicing we have to give start:end of both row and col
ar[1:4,3]
# For slicing we have to give start:end of both row and col
ar[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [47]:
## Mask
# Consider array
ar=np.arange(25).reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
# Now if we want to get values which are divisible by 5
ar[ar%5==0]

array([ 0,  5, 10, 15, 20])

In [49]:
# Similarly we can add more than one condition as
ar[(ar%5==0) & (ar%10==0)]

array([ 0, 10, 20])

In [51]:
# We can also find a value and place something at those location full filling condition
np.where(ar%5==0,"Y","N")

array([['Y', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N']], dtype='<U1')

In [52]:
#For multiplication conditions
np.where((ar%5==0) & (ar%10==0),"Y","N")

array([['Y', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'N', 'N'],
       ['Y', 'N', 'N', 'N', 'N']], dtype='<U1')

In [55]:
# Staking 
a=np.arange(25).reshape(5,5)
b=np.arange(25,50).reshape(5,5)
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [57]:
np.stack((a,b))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [58]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [59]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])